{
 "title": "Apache Tomcat",
 "description": "Tomcat dashboard using metrics from prometheus JMX exporter, with drill down per job > instance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(tomcat_threadpool_connectioncount,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(tomcat_threadpool_connectioncount{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(tomcat_threadpool_connectioncount{namespace=~\"$namespace\",job=~\"$job\"},app)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(tomcat_threadpool_connectioncount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\"},instance)"
    }
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(tomcat_threadpool_connectioncount{namespace=~\"$namespace\",job=~\"$job\",instance=~\"$instance\",app=~\"$app\"},pod)"
    }
   },
   {
    "name": "port",
    "label": "Port",
    "query": {
     "query": "label_values(tomcat_bytesreceived_total{namespace=~\"$namespace\",job=~\"$job\", app=~\"$app\",instance=~\"$instance\"},port)"
    }
   },
   {
    "name": "protocol",
    "label": "Protocol",
    "query": {
     "query": "label_values(tomcat_bytesreceived_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",port=~\"$port\"},protocol)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WebResource Cache Performance (${app})",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "WebResource Cache Size",
     "type": "stat",
     "description": "Current size (in kilobytes) of the combined web apps cache",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum( tomcat_cache_size{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"} )",
       "legendFormat": "{{context}}"
      }
     ]
    },
    {
     "title": "Max. Cache Size",
     "type": "stat",
     "description": "Maximum size (in kilobytes) that a resource can be to cached.  Careful, showing the largest configured cache across all web apps, which may not be the one that you're watching.",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max( tomcat_cache_maxsize{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"} )",
       "legendFormat": "{{context}}"
      }
     ]
    },
    {
     "title": "Ratios",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expression": "${CacheHitCount} / ${ValidRequestCount}",
       "reducer": "mean",
       "type": "math"
      },
      {
       "expression": "${CacheLookupCount} / ${ValidRequestCount}",
       "reducer": "mean",
       "type": "math"
      },
      {
       "expression": "(${CacheLookupCount} - ${CacheHitCount}) / ${ValidRequestCount}",
       "reducer": "mean",
       "type": "math"
      }
     ]
    },
    {
     "title": "Ratio Trend",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 15, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expression": "${CacheLookupCount} / ${ValidRequestCount}",
       "reducer": "mean",
       "type": "math"
      },
      {
       "expression": "${CacheHitCount} / ${ValidRequestCount}",
       "reducer": "mean",
       "type": "math"
      }
     ]
    },
    {
     "title": "Requests",
     "type": "stat",
     "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expression": "${CacheHitCount}", "reducer": "mean", "type": "math" },
      { "expression": "${CacheLookupCount}", "reducer": "mean", "type": "math" },
      {
       "expression": "${CacheLookupCount} - ${CacheHitCount}",
       "reducer": "mean",
       "type": "math"
      }
     ]
    },
    {
     "title": "Max. Object Size",
     "type": "stat",
     "description": "Maximum size (in kilobytes) that a resource can be to cached.  Careful, dashboard shows max across all web apps which may not be the one you are watching.",
     "gridPos": { "h": 3, "w": 2, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "deckbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max( tomcat_cache_objectmaxsize{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"} )",
       "legendFormat": "{{context}}"
      }
     ]
    },
    {
     "title": "Cache TTL",
     "type": "stat",
     "description": "Approximate time (in milliseconds) that an object will persist in the cache.  Careful, showing maximum TTL setting across all registered web apps which may not be the web app you're watching.",
     "gridPos": { "h": 3, "w": 2, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max( tomcat_cache_ttl{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"} )",
       "legendFormat": "{{context}}"
      }
     ]
    },
    {
     "title": "Requests and Caching Performance Metrics",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "rate(tomcat_cache_lookupcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__rate_interval]) != 0",
       "legendFormat": "Eligible request rate [{{context}}]"
      },
      {
       "expr": "rate(tomcat_requestcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval]) != 0",
       "legendFormat": "Request rate [{{protocol}}:{{port}}]"
      },
      {
       "expr": "rate(tomcat_errorcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval]) != 0",
       "legendFormat": "Error rate [{{protocol}}:{{port}}]"
      },
      {
       "expr": "rate(tomcat_cache_hitcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__rate_interval]) != 0",
       "legendFormat": "Cache hit rate [{{context}}]"
      }
     ]
    }
   ]
  },
  {
   "title": "Protocol [$protocol]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "repeat": "protocol",
   "targets": [
    {}
   ]
  },
  {
   "title": "Max threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_maxthreads{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Min spare threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_minsparethreads{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Busy threads",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Accept count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Acceptor thread count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_acceptorthreadcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Poller thread count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "tomcat_threadpool_pollerthreadcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "{{pod}}:{{port}}"
    }
   ]
  },
  {
   "title": "Connections ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threadpool_connectioncount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "connections - {{protocol}}[{{pod}}:{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_keepalivecount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "keep alive connections - {{protocol}}[{{pod}}:{{port}}]"
    }
   ]
  },
  {
   "title": "Transaction Rate ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(tomcat_requestcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval])",
     "legendFormat": "transaction rate - {{protocol}}[{{pod}}:{{port}}]"
    },
    {
     "expr": "rate(tomcat_errorcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval])",
     "legendFormat": "error rate - {{protocol}}[{{pod}}:{{port}}]"
    }
   ]
  },
  {
   "title": "Service Latency ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum( increase(tomcat_processingtime_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval]) ) by (instance, pod, port))\n    /\n(sum(increase(tomcat_requestcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval]) ) by (instance, pod, port))",
     "legendFormat": "processing time - {{protocol}}[{{pod}}:{{port}}]"
    }
   ]
  },
  {
   "title": "Network Traffic ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(tomcat_bytesreceived_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval])",
     "legendFormat": " bytes received - {{protocol}}[{{pod}}:{{port}}]"
    },
    {
     "expr": "rate(tomcat_bytessent_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}[$__rate_interval])*-1",
     "legendFormat": "bytes sent - {{protocol}}[{{pod}}:{{port}}]"
    },
    {
     "expr": "rate(catalina_https_jsse_nio2_8443_bytesreceived{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval])",
     "legendFormat": " WS bytes received"
    },
    {
     "expr": "(rate(catalina_https_jsse_nio2_8443_bytessent{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval]))*-1",
     "legendFormat": "WS bytes sent"
    }
   ]
  },
  {
   "title": "WebSocket Message Rate",
   "type": "timeseries",
   "description": "WARNING: the present instrumentation does not allow adding the protocol label to this metric, and hence it will not filter as the others based on the interface.",
   "gridPos": { "h": 10, "w": 6, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(catalina_https_jsse_nio2_8443_msgsreceived{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval])",
     "legendFormat": "WS message receive rate"
    },
    {
     "expr": "(rate(catalina_https_jsse_nio2_8443_msgssent{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval]))*-1",
     "legendFormat": "WS message send rate"
    },
    {
     "expr": "rate(catalina_https_jsse_nio_8443_msgsreceived{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval])",
     "legendFormat": "WS message receive rate"
    },
    {
     "expr": "(rate(catalina_https_jsse_nio_8443_msgssent{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",Upgrade=\"websocket\"}[$__rate_interval]))*-1",
     "legendFormat": "WS message send rate"
    }
   ]
  },
  {
   "title": "Thread Pool ($protocol)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "tomcat_threadpool_currentthreadcount{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "current threads - [{{pod}}:{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_currentthreadsbusy{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "currently busy - [{{pod}}:{{port}}]"
    },
    {
     "expr": "tomcat_threadpool_maxthreads{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\",protocol=~\"$protocol\",port=~\"$port\"}",
     "legendFormat": "max threads - [{{pod}}:{{port}}]"
    }
   ]
  },
  {
   "title": "Servlet stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Session count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(tomcat_session_sessioncounter_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval])) by (instance, pod)",
     "legendFormat": "New - {{pod}}"
    },
    {
     "expr": "sum(increase(tomcat_session_expiredsessions_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval])) by (instance, pod)",
     "legendFormat": "Expired - {{pod}}"
    },
    {
     "expr": "sum(increase(tomcat_session_rejectedsessions_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval])) by (instance, pod)",
     "legendFormat": "Rejected - {{pod}}"
    }
   ]
  },
  {
   "title": "Session current count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"} - tomcat_session_expiredsessions_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Session total created",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tomcat_session_sessioncounter_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Session total expired",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(tomcat_session_expiredsessions_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Top 5 servlet request count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_requestcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}} pod={{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 servlet error count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_errorcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "module={{module}} servlet={{servlet}} pod={{pod}}"
    }
   ]
  },
  {
   "title": "Top 5 servlets average processing time per request",
   "type": "timeseries",
   "description": "Top 4 servlets average processing time per request in last 5 minutes",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "topk(5, increase(tomcat_servlet_processingtime_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval]) / increase(tomcat_servlet_requestcount_total{namespace=~\"$namespace\",job=~\"$job\",app=~\"$app\",instance=~\"$instance\",pod=~\"$pod\"}[$__interval]))",
     "legendFormat": "module {{module}} servlet {{servlet}} pod {{pod}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 77 },
   "options": {
    "content": "Dashboard version: 2.1\\\nInstrumentation: JMX Exporter installed in JVM as Java agent\\\nJMX Exporter configuration: Custom configuration (shared) adding specific MBean attributes\\\nEnhanced by: Greg Eva - Enterprise Architecture Community Lead, PTC\\\nContact e-mail: geva@ptc.com"
   },
   "targets": [
    {}
   ]
  }
 ]
}