{
 "title": "Couchbase Cluster Overview",
 "description": "Couchbase cluster overview: Monitors cluster status, each node status, resources (CPU/Mem/Disk) per node, rebalance status, and bucket stats.",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(cbnode_up, cluster)"
    }
   },
   {
    "name": "node",
    "label": "node",
    "query": {
     "query": "label_values(cbnode_healthy{cluster=\"$cluster\"}, node)"
    }
   },
   {
    "name": "bucket",
    "label": "bucket",
    "query": {
     "query": "label_values(cbbucketinfo_basic_dataused_bytes{cluster=~\"$cluster\"}, bucket)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster Info:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_up{cluster=\"cb.uat.whizmo.ae\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Each Node Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_healthy{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Each Node: Up Time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_uptime{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Each Node: CPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 13, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "cbnode_systemstats_cpu_utilization_rate{cluster=\"$cluster\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Each Node: Memory Used",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_memory_total{cluster=\"$cluster\"} - cbnode_memory_free{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Each Node: Disk Used",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_interestingstats_couch_docs_actual_disk_size{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rebalance Status",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cbnode_rebalance_start{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbnode_rebalance_success{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbnode_rebalance_failure{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bucket Info:", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Buckets Info",
   "type": "table",
   "gridPos": { "h": 23, "w": 24, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "cbbucketinfo_basic_itemcount{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbbucketstat_vbuckets_active_resident_items_ratio{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbbucketstat_ops{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbbucketinfo_basic_diskused_bytes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbbucketinfo_basic_memused_bytes{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "cbbucketinfo_basic_quota_user_percent{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}